\" zs - work with, and move objects from one AS/400 to another.
\" Copyright (C) 2018  Andreas Louv <andreas@louv.dk>
\" See LICENSE
.TH ZS\-ANALYZE 1
.SH NAME
ZS\-ANALYZE \- Print depends and dependencies for objects
.SH SYNOPSIS
.B zs\-analyze
[\fIOPTION\fR]... \fIOBJECT\fR...
.SH DESCRIPTION
zs\-analyze prints depends and dependencies for objects
.SH OPTIONS
.PP
Options like \fB-c\fR can be specified multiple times each adding to the
previous result set.
.TP
\fB\-s\fR \fIHOST\fR
set source host
.TP
\fB\-u\fR \fIUSER\fR
set source user
.TP
\fB\-p\fR \fIPORT\fR
set source port
.TP
\fB\-m\fR \fITRIES\fR
set maximum tries for source to respond
.IP
a timeout will occur when the server have not responded to a pull
.I TRIES
times, between each pull 250 milliseconds delay will occur
.TP
\fB\-c\fR \fIFILE\fR
source configuration file
.IP
a file following the schema defined in
.BR zs-config (5)
.IP
can be specified multiple times
.TP
\fB\-v\fR
level of verbosity
.IP
can be specified multiple times, each additional time provides more verbosity
.TP
\fB\-V\fR
option version information and exit
.TP
\fB\-h\fR
show help message and exit
.SS "Exit status:"
.TP
0
if OK,
.TP
1
if any problem,
.TP
2
if provided command\-line arguments wrong.
.SH OBJECTS
At least one object needs specified.
.PP
An object takes the following form:
.PP
.RS
\fILIBRARY\fR\fB/\fR\fIOBJECT\fR
.RE
.SH SEE ALSO
.BR zs (1),
.BR zs-config (5)
