.TH zs 1
.SH "NAME"
zs \- Copy objects from one AS/400 to another

.SH "SYNOPSIS"

zs { { -s=server | -u=user | -p=password | -j=file | -c=file }...
     { -S=server | -U=user | -P=password | -J=file | -C=file }...
     { LIB/OBJ [ *TYPE ] }...
     | --help | --version }

.SH "DESCRIPTION"
zs copies objects from one AS/400 to another via FTP.

.SH "OPTIONS"

Each option is read in sequence making it possible to override options via a
later defined config file.

.IP "\fB-s\fR, \fB--source-server\fR=\fIserver\fR"
set source server

.IP "\fB-u\fR, \fB--source-user\fR=\fIuser\fR"
set source user profile

.IP "\fB-p\fR, \fB--source-password\fR=\fIpassword\fR"
set source user password

.IP "\fB-c\fR, \fB--source-config\fR=\fIfile\fR"
path to source config

.IP "\fB-j\fR, \fB--source-job-log\fR=\fIfile\fR"
path to source joblog

.IP "\fB-S\fR, \fB--target-server\fR=\fIserver\fR"
set target server

.IP "\fB-U\fR, \fB--target-user\fR=\fIuser\fR"
set target user profile

.IP "\fB-P\fR, \fB--target-password\fR=\fIpassword\fR"
set target user password

.IP "\fB-L\fR, \fB--target-library\fR=\fIlibrary\fR"
set target library

.IP "\fB-C\fR, \fB--target-config\fR=\fIfile\fR"
path to target config

.IP "\fB-J\fR, \fB--target-job-log\fR=\fIfile\fR"
path to target joblog

.IP "\fB-v\fR, \fB--verbose\fR"
level of verbosity, can be specified multiply times.  Should be the first
option, as it affect the verbosity of other options.

.IP "\fB-V\fR, \fB--version\fR"
output version information and exit

.IP "\fB-h\fR, \fB--help\fR"
show this help message and exit

.SH "OBJECTS"

An object takes the following form:

.RS
{ LIBRARY "/" OBJECT *TYPE | LIBRARY "/" OBJECT }
.RE

\fILIBRARY\fR is the library where the object recites, max. 10 characters.

\fIOBJECT\fR is the object, max. 10 characters.

\fITYPE\fR is an optional type to transfer, \fB*ALL\fR is used when omitted.
Consult your local system administrator for a list of supported types.

.SH "CONFIG"
A config file takes the following form:

.RS
{ \fI"#"\fR .* | \fIKEY\fR \fISP\fR+ \fIVALUE\fR }
.RE

\fI#\fR marks a comment to the end of the line

\fIKEY\fR is one of the following:
\fBuser\fR,
\fBpassword\fR,
\fBserver\fR, and
\fBjoblog\fR.

\fISP\fR is one or more of space (0x20) and tab characters (0x09)

\fIVALUE\fR can be any character except a newline (0x0A)

Making a valid configuration file containing username and password look like
this:

.RS
user QSEQOFR
.bp
password secure
.RE
