\" zs - work with, and move objects from one AS/400 to another.
\" Copyright (C) 2018  Andreas Louv <andreas@louv.dk>
\" See LICENSE
.TH ZS 1
.SH NAME
ZS \- Work with objects on an AS/400
.SH SYNOPSIS
.B zs\-analyze
{ \fIOPTION\fR | \fICOMMAND\fR [\fIOPTION\fR]... }
.SH DESCRIPTION
zs \- work with, and move objects from one AS/400 to another.
.PP
Analyze dependencies for files
.SH OPTIONS
.PP
.TP
\fB\-V\fR
option version information and exit
.TP
\fB\-h\fR
show help message and exit
.SS "Exit status:"
.TP
0
if OK,
.TP
1
if any problem,
.TP
2
if provided command\-line arguments wrong.
.SH FILES
/etc/zs/default.conf
.SH SEE ALSO
.BR zs-copy (1),
.BR zs-analyze (1)
